Draft: Script and Alert Logic Enhancements
lmegviar/warm-line-integration pull request #18
Opened 2024-04-27 21:13 UTC by rsteckline

Changes
- Added try-catch blocks around asynchronous calls for better error handling
- Ensured scripts execute after the DOM is fully loaded for consistency
- Implemented direct user alerts to log in
- Modified tab to open as active when GoTo log in is needed

References
- Chrome Extension Scripting [Kaushik's Dev.to article](https://dev.to/awalakaushik/execute-a-function-with-arguments-using-chrome-extension-scripting-api-2b7m).
- Applied practices for DOMContentLoaded from [MDN Web Docs](https://developer.mozilla.org/en-US/docs/Web/API/Document/DOMContentLoaded_event).

2024-04-27 21:25 UTC, rsteckline commented
I added `try...catch` blocks to ensure that any errors encountered during these operations are caught and logged, rather than causing unhandled promise rejections which could lead to unpredictable script behavior.

The addition of the `DOMContentLoaded` event listener in goTo.js was to refactor for improved script initialization. It should ensure that the login alert only shows up when the document has fully loaded, preventing premature execution of the script. I intended for the new code to check if the user is on the login page actively and, if so, prompt them with an alert to log in instead of relying on background scripts or passive indicators.

2024-04-27 22:03 UTC, lmegviar requested changes
Thanks for sharing your WIP! Let me know if you have any questions about the comments or want to talk through ideas.

2024-04-27 22:03 UTC, lmegviar commented on service-worker.js
> +        active: true //Ensures tab is visible to the operator
Good idea, but they would prefer the tab to not be visible. Ideally, as much will happen "behind the scenes" as possible. One alternative would be to trigger a pop up in the user's current tab. Alternatively, you could just make the tab active in the cases of needing to login, but allow it to remain in the background otherwise.

2024-04-27 22:03 UTC, lmegviar commented on goTo.js
> +document.addEventListener("DOMContentLoaded", function () {
This script is only injected into the GoTo profile creation page (see line 48 of `service_worker.js`). Basically it's just added as another script element on that page. When it redirects to the login page, that script element is no longer present so this won't be triggered in that context.

One approach would updating `initiateGoToProfile` to use other content script(s) to handle hitting the login page and then retying once the new contact page reloads after logging in.

2024-04-27 22:03 UTC, lmegviar commented on manifest.json
> +    "web_accessible_resources": [
Is this required?

2024-06-16 18:27 UTC, lmegviar commented
Closing for now, but we can re-open if you have time to revisit this.

2024-06-16 18:27 UTC, closed without merging